[package]
name = "vaultrs"
version = "0.3.0"
authors = ["Joshua Gilman <joshuagilman@gmail.com>"]
description = "An asynchronous Rust client library for the Hashicorp Vault API."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jmgilman/vaultrs"
keywords = ["Vault", "API", "Client", "Hashicorp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
bytes = "1.0.1"
derive_builder = "0.10.2"
http = "0.2.4"
log = "0.4.14"
reqwest = { version = "0.11.4", features = ["json"] }
rustify = "0.4.2"
rustify_derive = "0.4.2"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
serde_with = "1.9.4"
thiserror = "1.0.26"
url = "2.2.2"

[dev-dependencies]
env_logger = "0.9.0"
httpmock = "0.5.8"
testcontainers = "0.12.0"
test-env-log = "0.2.7"
tokio = "1.10.1"
tokio-test = "0.4.2"
