[package]
name = "vaultrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.10.2"
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
rustify = { path = "../rustify" }
rustify_derive = { path = "../rustify/rustify_derive" }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
serde_with = "1.9.4"
thiserror = "1.0.26"
url = "2.2.2"

[dev-dependencies]
testcontainers = "0.12.0"