[package]
name = "vaultrs"
version = "0.4.0"
authors = ["Joshua Gilman <joshuagilman@gmail.com>"]
description = "An asynchronous Rust client library for the Hashicorp Vault API."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jmgilman/vaultrs"
keywords = ["Vault", "API", "Client", "Hashicorp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
oidc = ["tiny_http", "tokio"]

[dependencies]
async-trait = "0.1.51"
bytes = "1.0.1"
derive_builder = "0.10.2"
http = "0.2.4"
log = "0.4.14"
reqwest = { version = "0.11.4", features = ["json"] }
rustify = "0.4.3"
rustify_derive = "0.4.3"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
serde_with = "1.9.4"
tokio = { version = "1.10.1", optional = true }
thiserror = "1.0.26"
tiny_http = { version = "0.8.2", optional = true }
url = "2.2.2"
dirs = "3.0.2"

[dev-dependencies]
tokio-test = "0.4.2"
vaultrs-test = { version = "0.2.0", path = "./vaultrs-test" }