[package]
name = "vaultrs-login"
version = "0.1.5"
authors = ["Joshua Gilman <joshuagilman@gmail.com>"]
description = "Adds login support for Vault clients from vaultrs."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jmgilman/vaultrs"
keywords = ["Vault", "API", "Client", "Hashicorp", "Login"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
oidc = ["tiny_http", "tokio"]

[dependencies]
async-trait = "0.1.52"
serde = "1.0.136"
tiny_http = { version = "0.11.0", optional = true }
tokio = { version = "1.17.0", optional = true }
url = "2.2.2"
vaultrs = { version = "0.6.0", path = ".." }
tracing = "0.1.32"

[dev-dependencies]
reqwest = "0.11.10"
tokio-test = "0.4.2"
tracing-test = "0.2.1"
dockertest-server = { version = "0.1.6", features = ["hashi", "auth"] }
