[package]
name = "vaultrs-login"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
oidc = ["tiny_http", "tokio"]

[dependencies]
async-trait = "0.1.51"
serde = "1.0.130"
tiny_http = { version = "0.8.2", optional = true }
tokio = { version = "1.11.0", optional = true }
url = "2.2.2"
vaultrs = { version = "0.4.0", path = "../" }

[dev-dependencies]
reqwest = "0.11.4"
vaultrs-test = "0.2.0"